### ISSUE TITLE
Installing issues

### ISSUE THREAD

**Issue by gustavomr** [samhita-alla/video-translation#1]
Hi,

Thanks for your great project but I cannot installing it locally because a lot of problems during dependency installing.

I´m trying to create a conda env with python 3.10 and executing pip install -r dev_requirements.txt but getting a lot of dependency erros. 

Could you provide a way to installing it correctly?

Thanks for all!

**Comment by samhita-alla** [comment]
@gustavomr thanks for checking out this project! could you try installing in a python 3.11 environment? apologies for not mentioning the version in the README. i'd recommend you run this on a locally spup up flyte cluster, so that way you needn't worry about installing the libraries locally except for `flytekit`, and you'll need to remove `builder` and add `registry` to `ImageSpec`.

**Comment by gustavomr** [comment]
@samhita-alla First, thanks for sharing your project, it´s amazing!  

I´ve tried update do python 3.11 but getting some errors with 3.11 version. I´ve downgraded to 3.10 but showed for me a lot of problems with the dependencies as well.

  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\gmr\AppData\Local\Temp\pip-install-qdcy4ozv\numba_7e9a985430d045f6b9867bfd8d99fb07\setup.py", line 51, in <module>
          _guard_py_ver()
        File "C:\Users\gmr\AppData\Local\Temp\pip-install-qdcy4ozv\numba_7e9a985430d045f6b9867bfd8d99fb07\setup.py", line 48, in _guard_py_ver
          raise RuntimeError(msg.format(cur_py, min_py, max_py))
      RuntimeError: Cannot install on Python version 3.11.9; only versions >=3.7,<3.11 are supported.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by samhita-alla** [comment]
@gustavomr updated the requirements. would you mind trying now?
